Version 7.15.2 added to the Dockerfile
AlphaFounders/docker-elk pull request #6
Opened 2024-08-21 03:12 UTC by ShaunGautham

2024-08-21 03:20 UTC, nitheesb approved these changes

2024-08-21 06:34 UTC, mithRabbit commented on elasticsearch/Dockerfile
> +FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.2
can you update the ENV instead not here

2024-08-21 14:53 UTC, gowriter approved these changes

2024-08-21 14:53 UTC, gowriter commented on elasticsearch/Dockerfile
> +FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.2
i would recommend getting rid of this useless env var, dev should decide what version. approved!

2024-08-22 06:55 UTC, gowriter commented on elasticsearch/Dockerfile
> +FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.2
After discussing this change with mithlash, i agree with him, should update the env

2024-08-22 11:02 UTC, JeremyRms requested changes
Agreed with Mithlesh, please update the env file instead

2024-08-23 11:18 UTC, JeremyRms approved these changes

2024-08-23 11:19 UTC, merged